function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 11-Feb-2019 05:54:25

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','The Proposed method','Marker','o');
set(plot1(2),'DisplayName','Covariance based detection','Marker','x',...
    'Color',[1 0 0]);
set(plot1(3),'DisplayName','Time-frequency ridge energy','Marker','*',...
    'Color',[1 1 0]);
set(plot1(4),'DisplayName','Energy detection','LineStyle','--',...
    'Color',[0 0 0]);
set(plot1(5),'DisplayName','Conventional IF method','LineStyle','--',...
    'Color',[0 1 0]);

% Create ylabel
ylabel('Detection Probability');

% Create xlabel
xlabel('Signal to noise ratio (dB)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-10 4]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1]);
box(axes1,'on');
% Create legend
legend(axes1,'show');

